version: '3.8'
name: test-symfony

services:
  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: test-symfony-symfony
    volumes:
      - ./app:/var/www/app
      - ./php/config/php.ini:/etc/php/8.2/fpm/conf.d/99-php.ini
    working_dir: /var/www/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PHP_IDE_CONFIG: 'serverName=App'
    depends_on:
      - postgres
    command: php-fpm
    networks:
      - test-symfony

  nginx:
    image: nginx:latest
    container_name: test-symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - test-symfony

  postgres:
    image: postgres:15
    container_name: test-symfony-postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - test-symfony

volumes:
  postgres_data:

networks:
  test-symfony:
    driver: bridge
